version: "3.9"

networks:
  main-network:
    name: main-network
    external: false
    driver: bridge

services:

  redpanda-1:
    # NOTE: Please use the latest version here!
    image: docker.redpanda.com/vectorized/redpanda:latest
    container_name: redpanda-1
    ports:
      - "9092:9092"
#      - "29092:29092"
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --check=false
      - --rpc-addr 0.0.0.0:33145
      - --advertise-rpc-addr redpanda-1:33145
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda-1:29092,OUTSIDE://localhost:9092
    networks:
      - main-network
    restart: unless-stopped

  redpanda-2:
    # NOTE: Please use the latest version here!
    image: docker.redpanda.com/vectorized/redpanda:latest
    container_name: redpanda-2
    ports:
      - "9093:9093"
#      - "29093:29093"
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 1
      - --seeds "redpanda-1:33145"
      - --check=false
      - --rpc-addr 0.0.0.0:33146
      - --advertise-rpc-addr redpanda-2:33146
      - --kafka-addr PLAINTEXT://0.0.0.0:29093,OUTSIDE://0.0.0.0:9093
      - --advertise-kafka-addr PLAINTEXT://redpanda-2:29093,OUTSIDE://localhost:9093
    networks:
      - main-network
    restart: unless-stopped

  redpanda-3:
    # NOTE: Please use the latest version here!
    image: docker.redpanda.com/vectorized/redpanda:latest
    container_name: redpanda-3
    ports:
      - "9094:9094"
#      - "29094:29094"
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 2
      - --seeds "redpanda-2:33146"
      - --check=false
      - --rpc-addr 0.0.0.0:33147
      - --advertise-rpc-addr redpanda-3:33147
      - --kafka-addr PLAINTEXT://0.0.0.0:29094,OUTSIDE://0.0.0.0:9094
      - --advertise-kafka-addr PLAINTEXT://redpanda-3:29094,OUTSIDE://localhost:9094
    networks:
      - main-network
    restart: unless-stopped

  kafka-console:
    image: docker.redpanda.com/vectorized/console:latest
    container_name: kafka-console
    ports:
      - "9090:8080"
    environment:
      - KAFKA_BROKERS=redpanda-1:29092,redpanda-2:29093,redpanda-3:29094
    networks:
      - main-network
    restart: unless-stopped
